# Generated by Django 3.0.4 on 2020-04-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='country')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='province')),
                ('neighbourhood', models.CharField(blank=True, max_length=30, verbose_name='neighbourhood')),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='intersts',
            new_name='interests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Music'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='music',
            field=models.ManyToManyField(blank=True, to='music.User_top_music'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.CharField(blank=True, default='0', max_length=100000000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='top_artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spotify_token',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='spotify token'),
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_owner', to=settings.AUTH_USER_MODEL)),
                ('s_users', models.ManyToManyField(blank=True, related_name='s_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserLocation', verbose_name='location'),
        ),
    ]
