# Generated by Django 3.0.4 on 2020-04-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('account', '0002_auto_20200329_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='username')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='nickname')),
                ('spotify_token', models.CharField(blank=True, max_length=220, null=True, verbose_name='spotify token')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Music'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='music',
            field=models.ManyToManyField(to='music.User_top_music'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(to='account.Friends'),
        ),
    ]
