# Generated by Django 3.0.5 on 2020-04-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200418_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='music',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='created',
        ),
    ]
