# Generated by Django 3.0.4 on 2020-04-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200402_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='intersts',
            new_name='interests',
        ),
    ]
