# Generated by Django 3.0.4 on 2020-04-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200402_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='biography',
        ),
    ]
