# Generated by Django 3.0.4 on 2020-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('account', '0006_auto_20200403_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='account.Friends'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='music',
            field=models.ManyToManyField(blank=True, to='music.User_top_music'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spotify_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='spotify token'),
        ),
    ]
