# Generated by Django 3.2 on 2023-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(blank=True, max_length=250, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('spotify_url', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(blank=True, max_length=250, null=True)),
                ('track_name', models.CharField(blank=True, max_length=250, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('spotify_url', models.CharField(blank=True, max_length=250, null=True)),
                ('album', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
