# Generated by Django 3.0.5 on 2020-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choices1', models.CharField(max_length=20)),
                ('choices2', models.CharField(max_length=20)),
                ('choices3', models.CharField(max_length=20)),
                ('choices4', models.CharField(default=None, max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('quiz_id', models.CharField(blank=True, default=None, max_length=200000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('choices1', models.CharField(max_length=20)),
                ('choices2', models.CharField(max_length=20)),
                ('choices3', models.CharField(max_length=20)),
                ('choices4', models.CharField(default=None, max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('quiz_id', models.CharField(blank=True, default=None, max_length=200000, null=True)),
            ],
        ),
    ]
