# Generated by Django 3.0.4 on 2020-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizimage',
            name='quiz_id',
            field=models.CharField(blank=True, default=None, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='quizpassage',
            name='quiz_id',
            field=models.CharField(blank=True, default=None, max_length=200000, null=True),
        ),
    ]
